### ISSUE TITLE
Running the binaries

### ISSUE THREAD

**Issue by IdanBanani** [limitedeternity/HeapLAB#1]
My bad, I probably damaged the files structure.

Anyway- do you have any idea how the files were compiled such that

1. RPATH is shown on on checksec
2. C code file (when avialable) is shown

**Comment by IdanBanani** [comment]
the answer was quite simple
1. use linker flags
2. use -g as an argument to gcc / CFLAGS (keep debug symbols)

something like this
```
CFLAGS=-g -Wall -no-pie -Wextra -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wl,-z,now -Wl,-z,relro,-z,noexecstack
LDFLAGS=-Wl,--rpath=../../.glibc/glibc_2.31/ -Wl,--dynamic-linker=../../.glibc/glibc_2.31/ld.so.2
```

**Comment by limitedeternity** [comment]
1. `.glibc` directory is too heavy for GitHub, I've [gitignore'd it](https://github.com/limitedeternity/HeapLAB/blob/8b1b76959a9f9cc0b3d321ae9fafbc593632e694/.gitignore#L131). Without it, the binaries won't run, obviously.
2. Yep, that's correct. The C code you see in pwndbg is mapped to assembly one using debug symbols.

Anyway, @IdanBanani , next time it's better to ask Max these questions, he is the instructor after all, not me.

**Comment by NobinPegasus** [comment]
@IdanBanani can you write all the commands that will let me run the binaries?
